W4D5_HW/MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:create, :new, :destroy]
  resources :bands
end

W4D5_HW/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W4D5_HW/MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  

end

W4D5_HW/MusicApp/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return user if user && user.is_password?(password)
    nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

W4D5_HW/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

W4D5_HW/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index # For view iterate thru @bands
    @bands = Band.all
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.create(band_params)

    redirect_to band_url(@band) if @band.save
  end

  def edit
    @band = Band.new
    render :edit
  end

  def update
    @band = Band.find_by(params[:id])

    
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5_HW/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:notice] = "Incorrect Credentials!"
      render :new
    end
  end

  def new
    if logged_in?
      return redirect_to user_url(current_user)
    end

    @user = User.new
    render :new
  end

  def destroy
    log_out_user!
    redirect_to new_session_url
  end

end

W4D5_HW/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = "422 Error"
    end
  end

  def new
    @user = User.new
    #render later
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  # def update
  #   user = User.find_by_credentials(params[:user][:email], params[:user][:password])
  #
  #   if user
  #     user.save!
  #   end
  # end
  #
  # def destroy
  #
  # end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5_HW/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
"<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

W4D5_HW/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Allerta+Stencil" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kumar+One+Outline" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://spliceblob.splice.com/lessons-of-kshmr/styles.2055e01b11f9a8418355.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="header">
    <h1 class="logo">MusicApp</h1>

    <% if current_user.nil? %>
      <a class="headerbutton" href="<%= new_session_url %>">Sign in</a>
      <a class="headerbutton" href="<%= new_user_url %>">Sign up</a>
    <% else %>
      <!-- <h2 class="header"><%#= current_user.email %></h2> -->
      <form action="<%= session_url %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <input class="headerbutton" type="submit" value="Logout">
      </form>
    <% end %>


    <div class="header-right">
      <a class="active" href="Songs">Songs</a>
      <a href="artists path">Artists</a>
      <a href="albums path">Albums</a>
    </div>
  </div>

  <body>

    <%= yield %>
  </body>
</html>

W4D5_HW/MusicApp/app/views/users/new.html.erb
<!-- sign up page -->
<section class="">
  <div class="">
    <h1>Create an account!</h1>

    <form action="<%= users_url %>" method="post">
      <%= auth_token %>
      <label>
        Email:
        <input type="text" name="user[email]" value="">
      </label>
      <br>
      <label>
        Password:
        <input type="password" name="user[password]" value="">
      </label>
      <br>
      <input type="submit" name="" value="Create account">
    </form>

  </div>
</section>

W4D5_HW/MusicApp/app/views/users/show.html.erb
<section class="">

  <div class="secondheader">
    <h1>Hello, <%= @user.email %>.</h1>
  </div>



</section>